app:
  domain: "78.154.103.37"
  port: "12152"
  uuid: "e88e0d74-af97-413f-b72a-d7c1078f60b4"
  xray-version: "25.10.15"
  hy2-version: "2.6.5"
  argo-version: "2025.10.0"
  argo-domain: "wispbyte.9943826.xyz"
  argo-token: ""
  remarks-prefix: "eyJhIjoiYTIyMWM5NDJhZTBjNDg0ZDNhMmZjNTM4NDI5ODMxZDQiLCJ0IjoiNmRiM2ZkYjItZWQ2ZC00ZWJlLWIyNjctMjk0MDEyMTAxMDMxIiwicyI6Ill6WmlNRFk0TlRndE9EVmpNaTAwT1RKbExUazROek10WXpnMllURTRNVEZqWXpGayJ9"
